import { UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { Socket } from 'socket.io';
import { WsJwtGuard } from './ws-jwt.guard';

type AcceptedTokenCase = {
  label: string;
  source: 'auth' | 'authorization' | 'Authorization' | 'authorization-array';
  authToken?: string;
  headerToken?: string | string[];
  expectedToken: string;
  expectedUserId: string;
  expectedSessionId: string;
  expectedWalletAddress: string;
};

type RejectedTokenCase = {
  label: string;
  source: 'none' | 'auth' | 'authorization' | 'Authorization';
  authToken?: string;
  headerToken?: string;
  verifyError?: string;
  payload?: Record<string, unknown>;
  expectedMessage: string;
};

const ACCEPTED_TOKEN_MATRIX: AcceptedTokenCase[] = [
  {
    label: 'signals auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-signals-feed',
    expectedToken: 'token-signals-feed',
    expectedUserId: 'user-token-signals-feed',
    expectedSessionId: 'session-token-signals-feed',
    expectedWalletAddress: 'user-token-signals-feed',
  },
  {
    label: 'signals auth bare token',
    source: 'auth',
    authToken: 'token-signals-feed-bare',
    expectedToken: 'token-signals-feed-bare',
    expectedUserId: 'user-token-signals-feed-bare',
    expectedSessionId: 'session-token-signals-feed-bare',
    expectedWalletAddress: 'user-token-signals-feed-bare',
  },
  {
    label: 'signals lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-signals-header',
    expectedToken: 'token-signals-header',
    expectedUserId: 'user-token-signals-header',
    expectedSessionId: 'session-token-signals-header',
    expectedWalletAddress: 'user-token-signals-header',
  },
  {
    label: 'signals uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-signals-upper',
    expectedToken: 'token-signals-upper',
    expectedUserId: 'user-token-signals-upper',
    expectedSessionId: 'session-token-signals-upper',
    expectedWalletAddress: 'user-token-signals-upper',
  },
  {
    label: 'signals array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-signals-array', 'Bearer ignored-token'],
    expectedToken: 'token-signals-array',
    expectedUserId: 'user-token-signals-array',
    expectedSessionId: 'session-token-signals-array',
    expectedWalletAddress: 'user-token-signals-array',
  },
  {
    label: 'trades auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-trades-feed',
    expectedToken: 'token-trades-feed',
    expectedUserId: 'user-token-trades-feed',
    expectedSessionId: 'session-token-trades-feed',
    expectedWalletAddress: 'user-token-trades-feed',
  },
  {
    label: 'trades auth bare token',
    source: 'auth',
    authToken: 'token-trades-feed-bare',
    expectedToken: 'token-trades-feed-bare',
    expectedUserId: 'user-token-trades-feed-bare',
    expectedSessionId: 'session-token-trades-feed-bare',
    expectedWalletAddress: 'user-token-trades-feed-bare',
  },
  {
    label: 'trades lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-trades-header',
    expectedToken: 'token-trades-header',
    expectedUserId: 'user-token-trades-header',
    expectedSessionId: 'session-token-trades-header',
    expectedWalletAddress: 'user-token-trades-header',
  },
  {
    label: 'trades uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-trades-upper',
    expectedToken: 'token-trades-upper',
    expectedUserId: 'user-token-trades-upper',
    expectedSessionId: 'session-token-trades-upper',
    expectedWalletAddress: 'user-token-trades-upper',
  },
  {
    label: 'trades array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-trades-array', 'Bearer ignored-token'],
    expectedToken: 'token-trades-array',
    expectedUserId: 'user-token-trades-array',
    expectedSessionId: 'session-token-trades-array',
    expectedWalletAddress: 'user-token-trades-array',
  },
  {
    label: 'portfolio auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-portfolio-feed',
    expectedToken: 'token-portfolio-feed',
    expectedUserId: 'user-token-portfolio-feed',
    expectedSessionId: 'session-token-portfolio-feed',
    expectedWalletAddress: 'user-token-portfolio-feed',
  },
  {
    label: 'portfolio auth bare token',
    source: 'auth',
    authToken: 'token-portfolio-feed-bare',
    expectedToken: 'token-portfolio-feed-bare',
    expectedUserId: 'user-token-portfolio-feed-bare',
    expectedSessionId: 'session-token-portfolio-feed-bare',
    expectedWalletAddress: 'user-token-portfolio-feed-bare',
  },
  {
    label: 'portfolio lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-portfolio-header',
    expectedToken: 'token-portfolio-header',
    expectedUserId: 'user-token-portfolio-header',
    expectedSessionId: 'session-token-portfolio-header',
    expectedWalletAddress: 'user-token-portfolio-header',
  },
  {
    label: 'portfolio uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-portfolio-upper',
    expectedToken: 'token-portfolio-upper',
    expectedUserId: 'user-token-portfolio-upper',
    expectedSessionId: 'session-token-portfolio-upper',
    expectedWalletAddress: 'user-token-portfolio-upper',
  },
  {
    label: 'portfolio array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-portfolio-array', 'Bearer ignored-token'],
    expectedToken: 'token-portfolio-array',
    expectedUserId: 'user-token-portfolio-array',
    expectedSessionId: 'session-token-portfolio-array',
    expectedWalletAddress: 'user-token-portfolio-array',
  },
  {
    label: 'leaderboard auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-leaderboard-feed',
    expectedToken: 'token-leaderboard-feed',
    expectedUserId: 'user-token-leaderboard-feed',
    expectedSessionId: 'session-token-leaderboard-feed',
    expectedWalletAddress: 'user-token-leaderboard-feed',
  },
  {
    label: 'leaderboard auth bare token',
    source: 'auth',
    authToken: 'token-leaderboard-feed-bare',
    expectedToken: 'token-leaderboard-feed-bare',
    expectedUserId: 'user-token-leaderboard-feed-bare',
    expectedSessionId: 'session-token-leaderboard-feed-bare',
    expectedWalletAddress: 'user-token-leaderboard-feed-bare',
  },
  {
    label: 'leaderboard lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-leaderboard-header',
    expectedToken: 'token-leaderboard-header',
    expectedUserId: 'user-token-leaderboard-header',
    expectedSessionId: 'session-token-leaderboard-header',
    expectedWalletAddress: 'user-token-leaderboard-header',
  },
  {
    label: 'leaderboard uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-leaderboard-upper',
    expectedToken: 'token-leaderboard-upper',
    expectedUserId: 'user-token-leaderboard-upper',
    expectedSessionId: 'session-token-leaderboard-upper',
    expectedWalletAddress: 'user-token-leaderboard-upper',
  },
  {
    label: 'leaderboard array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-leaderboard-array', 'Bearer ignored-token'],
    expectedToken: 'token-leaderboard-array',
    expectedUserId: 'user-token-leaderboard-array',
    expectedSessionId: 'session-token-leaderboard-array',
    expectedWalletAddress: 'user-token-leaderboard-array',
  },
  {
    label: 'contest auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-contest-feed',
    expectedToken: 'token-contest-feed',
    expectedUserId: 'user-token-contest-feed',
    expectedSessionId: 'session-token-contest-feed',
    expectedWalletAddress: 'user-token-contest-feed',
  },
  {
    label: 'contest auth bare token',
    source: 'auth',
    authToken: 'token-contest-feed-bare',
    expectedToken: 'token-contest-feed-bare',
    expectedUserId: 'user-token-contest-feed-bare',
    expectedSessionId: 'session-token-contest-feed-bare',
    expectedWalletAddress: 'user-token-contest-feed-bare',
  },
  {
    label: 'contest lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-contest-header',
    expectedToken: 'token-contest-header',
    expectedUserId: 'user-token-contest-header',
    expectedSessionId: 'session-token-contest-header',
    expectedWalletAddress: 'user-token-contest-header',
  },
  {
    label: 'contest uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-contest-upper',
    expectedToken: 'token-contest-upper',
    expectedUserId: 'user-token-contest-upper',
    expectedSessionId: 'session-token-contest-upper',
    expectedWalletAddress: 'user-token-contest-upper',
  },
  {
    label: 'contest array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-contest-array', 'Bearer ignored-token'],
    expectedToken: 'token-contest-array',
    expectedUserId: 'user-token-contest-array',
    expectedSessionId: 'session-token-contest-array',
    expectedWalletAddress: 'user-token-contest-array',
  },
  {
    label: 'copytrading auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-copytrading-feed',
    expectedToken: 'token-copytrading-feed',
    expectedUserId: 'user-token-copytrading-feed',
    expectedSessionId: 'session-token-copytrading-feed',
    expectedWalletAddress: 'user-token-copytrading-feed',
  },
  {
    label: 'copytrading auth bare token',
    source: 'auth',
    authToken: 'token-copytrading-feed-bare',
    expectedToken: 'token-copytrading-feed-bare',
    expectedUserId: 'user-token-copytrading-feed-bare',
    expectedSessionId: 'session-token-copytrading-feed-bare',
    expectedWalletAddress: 'user-token-copytrading-feed-bare',
  },
  {
    label: 'copytrading lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-copytrading-header',
    expectedToken: 'token-copytrading-header',
    expectedUserId: 'user-token-copytrading-header',
    expectedSessionId: 'session-token-copytrading-header',
    expectedWalletAddress: 'user-token-copytrading-header',
  },
  {
    label: 'copytrading uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-copytrading-upper',
    expectedToken: 'token-copytrading-upper',
    expectedUserId: 'user-token-copytrading-upper',
    expectedSessionId: 'session-token-copytrading-upper',
    expectedWalletAddress: 'user-token-copytrading-upper',
  },
  {
    label: 'copytrading array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-copytrading-array', 'Bearer ignored-token'],
    expectedToken: 'token-copytrading-array',
    expectedUserId: 'user-token-copytrading-array',
    expectedSessionId: 'session-token-copytrading-array',
    expectedWalletAddress: 'user-token-copytrading-array',
  },
  {
    label: 'premium auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-premium-feed',
    expectedToken: 'token-premium-feed',
    expectedUserId: 'user-token-premium-feed',
    expectedSessionId: 'session-token-premium-feed',
    expectedWalletAddress: 'user-token-premium-feed',
  },
  {
    label: 'premium auth bare token',
    source: 'auth',
    authToken: 'token-premium-feed-bare',
    expectedToken: 'token-premium-feed-bare',
    expectedUserId: 'user-token-premium-feed-bare',
    expectedSessionId: 'session-token-premium-feed-bare',
    expectedWalletAddress: 'user-token-premium-feed-bare',
  },
  {
    label: 'premium lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-premium-header',
    expectedToken: 'token-premium-header',
    expectedUserId: 'user-token-premium-header',
    expectedSessionId: 'session-token-premium-header',
    expectedWalletAddress: 'user-token-premium-header',
  },
  {
    label: 'premium uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-premium-upper',
    expectedToken: 'token-premium-upper',
    expectedUserId: 'user-token-premium-upper',
    expectedSessionId: 'session-token-premium-upper',
    expectedWalletAddress: 'user-token-premium-upper',
  },
  {
    label: 'premium array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-premium-array', 'Bearer ignored-token'],
    expectedToken: 'token-premium-array',
    expectedUserId: 'user-token-premium-array',
    expectedSessionId: 'session-token-premium-array',
    expectedWalletAddress: 'user-token-premium-array',
  },
  {
    label: 'mobile auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-mobile-feed',
    expectedToken: 'token-mobile-feed',
    expectedUserId: 'user-token-mobile-feed',
    expectedSessionId: 'session-token-mobile-feed',
    expectedWalletAddress: 'user-token-mobile-feed',
  },
  {
    label: 'mobile auth bare token',
    source: 'auth',
    authToken: 'token-mobile-feed-bare',
    expectedToken: 'token-mobile-feed-bare',
    expectedUserId: 'user-token-mobile-feed-bare',
    expectedSessionId: 'session-token-mobile-feed-bare',
    expectedWalletAddress: 'user-token-mobile-feed-bare',
  },
  {
    label: 'mobile lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-mobile-header',
    expectedToken: 'token-mobile-header',
    expectedUserId: 'user-token-mobile-header',
    expectedSessionId: 'session-token-mobile-header',
    expectedWalletAddress: 'user-token-mobile-header',
  },
  {
    label: 'mobile uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-mobile-upper',
    expectedToken: 'token-mobile-upper',
    expectedUserId: 'user-token-mobile-upper',
    expectedSessionId: 'session-token-mobile-upper',
    expectedWalletAddress: 'user-token-mobile-upper',
  },
  {
    label: 'mobile array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-mobile-array', 'Bearer ignored-token'],
    expectedToken: 'token-mobile-array',
    expectedUserId: 'user-token-mobile-array',
    expectedSessionId: 'session-token-mobile-array',
    expectedWalletAddress: 'user-token-mobile-array',
  },
  {
    label: 'browser auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-browser-feed',
    expectedToken: 'token-browser-feed',
    expectedUserId: 'user-token-browser-feed',
    expectedSessionId: 'session-token-browser-feed',
    expectedWalletAddress: 'user-token-browser-feed',
  },
  {
    label: 'browser auth bare token',
    source: 'auth',
    authToken: 'token-browser-feed-bare',
    expectedToken: 'token-browser-feed-bare',
    expectedUserId: 'user-token-browser-feed-bare',
    expectedSessionId: 'session-token-browser-feed-bare',
    expectedWalletAddress: 'user-token-browser-feed-bare',
  },
  {
    label: 'browser lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-browser-header',
    expectedToken: 'token-browser-header',
    expectedUserId: 'user-token-browser-header',
    expectedSessionId: 'session-token-browser-header',
    expectedWalletAddress: 'user-token-browser-header',
  },
  {
    label: 'browser uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-browser-upper',
    expectedToken: 'token-browser-upper',
    expectedUserId: 'user-token-browser-upper',
    expectedSessionId: 'session-token-browser-upper',
    expectedWalletAddress: 'user-token-browser-upper',
  },
  {
    label: 'browser array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-browser-array', 'Bearer ignored-token'],
    expectedToken: 'token-browser-array',
    expectedUserId: 'user-token-browser-array',
    expectedSessionId: 'session-token-browser-array',
    expectedWalletAddress: 'user-token-browser-array',
  },
  {
    label: 'api auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-api-feed',
    expectedToken: 'token-api-feed',
    expectedUserId: 'user-token-api-feed',
    expectedSessionId: 'session-token-api-feed',
    expectedWalletAddress: 'user-token-api-feed',
  },
  {
    label: 'api auth bare token',
    source: 'auth',
    authToken: 'token-api-feed-bare',
    expectedToken: 'token-api-feed-bare',
    expectedUserId: 'user-token-api-feed-bare',
    expectedSessionId: 'session-token-api-feed-bare',
    expectedWalletAddress: 'user-token-api-feed-bare',
  },
  {
    label: 'api lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-api-header',
    expectedToken: 'token-api-header',
    expectedUserId: 'user-token-api-header',
    expectedSessionId: 'session-token-api-header',
    expectedWalletAddress: 'user-token-api-header',
  },
  {
    label: 'api uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-api-upper',
    expectedToken: 'token-api-upper',
    expectedUserId: 'user-token-api-upper',
    expectedSessionId: 'session-token-api-upper',
    expectedWalletAddress: 'user-token-api-upper',
  },
  {
    label: 'api array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-api-array', 'Bearer ignored-token'],
    expectedToken: 'token-api-array',
    expectedUserId: 'user-token-api-array',
    expectedSessionId: 'session-token-api-array',
    expectedWalletAddress: 'user-token-api-array',
  },
  {
    label: 'wallet auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-wallet-feed',
    expectedToken: 'token-wallet-feed',
    expectedUserId: 'user-token-wallet-feed',
    expectedSessionId: 'session-token-wallet-feed',
    expectedWalletAddress: 'user-token-wallet-feed',
  },
  {
    label: 'wallet auth bare token',
    source: 'auth',
    authToken: 'token-wallet-feed-bare',
    expectedToken: 'token-wallet-feed-bare',
    expectedUserId: 'user-token-wallet-feed-bare',
    expectedSessionId: 'session-token-wallet-feed-bare',
    expectedWalletAddress: 'user-token-wallet-feed-bare',
  },
  {
    label: 'wallet lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-wallet-header',
    expectedToken: 'token-wallet-header',
    expectedUserId: 'user-token-wallet-header',
    expectedSessionId: 'session-token-wallet-header',
    expectedWalletAddress: 'user-token-wallet-header',
  },
  {
    label: 'wallet uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-wallet-upper',
    expectedToken: 'token-wallet-upper',
    expectedUserId: 'user-token-wallet-upper',
    expectedSessionId: 'session-token-wallet-upper',
    expectedWalletAddress: 'user-token-wallet-upper',
  },
  {
    label: 'wallet array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-wallet-array', 'Bearer ignored-token'],
    expectedToken: 'token-wallet-array',
    expectedUserId: 'user-token-wallet-array',
    expectedSessionId: 'session-token-wallet-array',
    expectedWalletAddress: 'user-token-wallet-array',
  },
  {
    label: 'admin auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-admin-feed',
    expectedToken: 'token-admin-feed',
    expectedUserId: 'user-token-admin-feed',
    expectedSessionId: 'session-token-admin-feed',
    expectedWalletAddress: 'user-token-admin-feed',
  },
  {
    label: 'admin auth bare token',
    source: 'auth',
    authToken: 'token-admin-feed-bare',
    expectedToken: 'token-admin-feed-bare',
    expectedUserId: 'user-token-admin-feed-bare',
    expectedSessionId: 'session-token-admin-feed-bare',
    expectedWalletAddress: 'user-token-admin-feed-bare',
  },
  {
    label: 'admin lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-admin-header',
    expectedToken: 'token-admin-header',
    expectedUserId: 'user-token-admin-header',
    expectedSessionId: 'session-token-admin-header',
    expectedWalletAddress: 'user-token-admin-header',
  },
  {
    label: 'admin uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-admin-upper',
    expectedToken: 'token-admin-upper',
    expectedUserId: 'user-token-admin-upper',
    expectedSessionId: 'session-token-admin-upper',
    expectedWalletAddress: 'user-token-admin-upper',
  },
  {
    label: 'admin array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-admin-array', 'Bearer ignored-token'],
    expectedToken: 'token-admin-array',
    expectedUserId: 'user-token-admin-array',
    expectedSessionId: 'session-token-admin-array',
    expectedWalletAddress: 'user-token-admin-array',
  },
  {
    label: 'risk auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-risk-feed',
    expectedToken: 'token-risk-feed',
    expectedUserId: 'user-token-risk-feed',
    expectedSessionId: 'session-token-risk-feed',
    expectedWalletAddress: 'user-token-risk-feed',
  },
  {
    label: 'risk auth bare token',
    source: 'auth',
    authToken: 'token-risk-feed-bare',
    expectedToken: 'token-risk-feed-bare',
    expectedUserId: 'user-token-risk-feed-bare',
    expectedSessionId: 'session-token-risk-feed-bare',
    expectedWalletAddress: 'user-token-risk-feed-bare',
  },
  {
    label: 'risk lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-risk-header',
    expectedToken: 'token-risk-header',
    expectedUserId: 'user-token-risk-header',
    expectedSessionId: 'session-token-risk-header',
    expectedWalletAddress: 'user-token-risk-header',
  },
  {
    label: 'risk uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-risk-upper',
    expectedToken: 'token-risk-upper',
    expectedUserId: 'user-token-risk-upper',
    expectedSessionId: 'session-token-risk-upper',
    expectedWalletAddress: 'user-token-risk-upper',
  },
  {
    label: 'risk array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-risk-array', 'Bearer ignored-token'],
    expectedToken: 'token-risk-array',
    expectedUserId: 'user-token-risk-array',
    expectedSessionId: 'session-token-risk-array',
    expectedWalletAddress: 'user-token-risk-array',
  },
  {
    label: 'settlement auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-settlement-feed',
    expectedToken: 'token-settlement-feed',
    expectedUserId: 'user-token-settlement-feed',
    expectedSessionId: 'session-token-settlement-feed',
    expectedWalletAddress: 'user-token-settlement-feed',
  },
  {
    label: 'settlement auth bare token',
    source: 'auth',
    authToken: 'token-settlement-feed-bare',
    expectedToken: 'token-settlement-feed-bare',
    expectedUserId: 'user-token-settlement-feed-bare',
    expectedSessionId: 'session-token-settlement-feed-bare',
    expectedWalletAddress: 'user-token-settlement-feed-bare',
  },
  {
    label: 'settlement lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-settlement-header',
    expectedToken: 'token-settlement-header',
    expectedUserId: 'user-token-settlement-header',
    expectedSessionId: 'session-token-settlement-header',
    expectedWalletAddress: 'user-token-settlement-header',
  },
  {
    label: 'settlement uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-settlement-upper',
    expectedToken: 'token-settlement-upper',
    expectedUserId: 'user-token-settlement-upper',
    expectedSessionId: 'session-token-settlement-upper',
    expectedWalletAddress: 'user-token-settlement-upper',
  },
  {
    label: 'settlement array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-settlement-array', 'Bearer ignored-token'],
    expectedToken: 'token-settlement-array',
    expectedUserId: 'user-token-settlement-array',
    expectedSessionId: 'session-token-settlement-array',
    expectedWalletAddress: 'user-token-settlement-array',
  },
  {
    label: 'alerts auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-alerts-feed',
    expectedToken: 'token-alerts-feed',
    expectedUserId: 'user-token-alerts-feed',
    expectedSessionId: 'session-token-alerts-feed',
    expectedWalletAddress: 'user-token-alerts-feed',
  },
  {
    label: 'alerts auth bare token',
    source: 'auth',
    authToken: 'token-alerts-feed-bare',
    expectedToken: 'token-alerts-feed-bare',
    expectedUserId: 'user-token-alerts-feed-bare',
    expectedSessionId: 'session-token-alerts-feed-bare',
    expectedWalletAddress: 'user-token-alerts-feed-bare',
  },
  {
    label: 'alerts lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-alerts-header',
    expectedToken: 'token-alerts-header',
    expectedUserId: 'user-token-alerts-header',
    expectedSessionId: 'session-token-alerts-header',
    expectedWalletAddress: 'user-token-alerts-header',
  },
  {
    label: 'alerts uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-alerts-upper',
    expectedToken: 'token-alerts-upper',
    expectedUserId: 'user-token-alerts-upper',
    expectedSessionId: 'session-token-alerts-upper',
    expectedWalletAddress: 'user-token-alerts-upper',
  },
  {
    label: 'alerts array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-alerts-array', 'Bearer ignored-token'],
    expectedToken: 'token-alerts-array',
    expectedUserId: 'user-token-alerts-array',
    expectedSessionId: 'session-token-alerts-array',
    expectedWalletAddress: 'user-token-alerts-array',
  },
  {
    label: 'analytics auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-analytics-feed',
    expectedToken: 'token-analytics-feed',
    expectedUserId: 'user-token-analytics-feed',
    expectedSessionId: 'session-token-analytics-feed',
    expectedWalletAddress: 'user-token-analytics-feed',
  },
  {
    label: 'analytics auth bare token',
    source: 'auth',
    authToken: 'token-analytics-feed-bare',
    expectedToken: 'token-analytics-feed-bare',
    expectedUserId: 'user-token-analytics-feed-bare',
    expectedSessionId: 'session-token-analytics-feed-bare',
    expectedWalletAddress: 'user-token-analytics-feed-bare',
  },
  {
    label: 'analytics lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-analytics-header',
    expectedToken: 'token-analytics-header',
    expectedUserId: 'user-token-analytics-header',
    expectedSessionId: 'session-token-analytics-header',
    expectedWalletAddress: 'user-token-analytics-header',
  },
  {
    label: 'analytics uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-analytics-upper',
    expectedToken: 'token-analytics-upper',
    expectedUserId: 'user-token-analytics-upper',
    expectedSessionId: 'session-token-analytics-upper',
    expectedWalletAddress: 'user-token-analytics-upper',
  },
  {
    label: 'analytics array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-analytics-array', 'Bearer ignored-token'],
    expectedToken: 'token-analytics-array',
    expectedUserId: 'user-token-analytics-array',
    expectedSessionId: 'session-token-analytics-array',
    expectedWalletAddress: 'user-token-analytics-array',
  },
  {
    label: 'orders auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-orders-feed',
    expectedToken: 'token-orders-feed',
    expectedUserId: 'user-token-orders-feed',
    expectedSessionId: 'session-token-orders-feed',
    expectedWalletAddress: 'user-token-orders-feed',
  },
  {
    label: 'orders auth bare token',
    source: 'auth',
    authToken: 'token-orders-feed-bare',
    expectedToken: 'token-orders-feed-bare',
    expectedUserId: 'user-token-orders-feed-bare',
    expectedSessionId: 'session-token-orders-feed-bare',
    expectedWalletAddress: 'user-token-orders-feed-bare',
  },
  {
    label: 'orders lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-orders-header',
    expectedToken: 'token-orders-header',
    expectedUserId: 'user-token-orders-header',
    expectedSessionId: 'session-token-orders-header',
    expectedWalletAddress: 'user-token-orders-header',
  },
  {
    label: 'orders uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-orders-upper',
    expectedToken: 'token-orders-upper',
    expectedUserId: 'user-token-orders-upper',
    expectedSessionId: 'session-token-orders-upper',
    expectedWalletAddress: 'user-token-orders-upper',
  },
  {
    label: 'orders array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-orders-array', 'Bearer ignored-token'],
    expectedToken: 'token-orders-array',
    expectedUserId: 'user-token-orders-array',
    expectedSessionId: 'session-token-orders-array',
    expectedWalletAddress: 'user-token-orders-array',
  },
  {
    label: 'liquidity auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-liquidity-feed',
    expectedToken: 'token-liquidity-feed',
    expectedUserId: 'user-token-liquidity-feed',
    expectedSessionId: 'session-token-liquidity-feed',
    expectedWalletAddress: 'user-token-liquidity-feed',
  },
  {
    label: 'liquidity auth bare token',
    source: 'auth',
    authToken: 'token-liquidity-feed-bare',
    expectedToken: 'token-liquidity-feed-bare',
    expectedUserId: 'user-token-liquidity-feed-bare',
    expectedSessionId: 'session-token-liquidity-feed-bare',
    expectedWalletAddress: 'user-token-liquidity-feed-bare',
  },
  {
    label: 'liquidity lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-liquidity-header',
    expectedToken: 'token-liquidity-header',
    expectedUserId: 'user-token-liquidity-header',
    expectedSessionId: 'session-token-liquidity-header',
    expectedWalletAddress: 'user-token-liquidity-header',
  },
  {
    label: 'liquidity uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-liquidity-upper',
    expectedToken: 'token-liquidity-upper',
    expectedUserId: 'user-token-liquidity-upper',
    expectedSessionId: 'session-token-liquidity-upper',
    expectedWalletAddress: 'user-token-liquidity-upper',
  },
  {
    label: 'liquidity array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-liquidity-array', 'Bearer ignored-token'],
    expectedToken: 'token-liquidity-array',
    expectedUserId: 'user-token-liquidity-array',
    expectedSessionId: 'session-token-liquidity-array',
    expectedWalletAddress: 'user-token-liquidity-array',
  },
  {
    label: 'execution auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-execution-feed',
    expectedToken: 'token-execution-feed',
    expectedUserId: 'user-token-execution-feed',
    expectedSessionId: 'session-token-execution-feed',
    expectedWalletAddress: 'user-token-execution-feed',
  },
  {
    label: 'execution auth bare token',
    source: 'auth',
    authToken: 'token-execution-feed-bare',
    expectedToken: 'token-execution-feed-bare',
    expectedUserId: 'user-token-execution-feed-bare',
    expectedSessionId: 'session-token-execution-feed-bare',
    expectedWalletAddress: 'user-token-execution-feed-bare',
  },
  {
    label: 'execution lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-execution-header',
    expectedToken: 'token-execution-header',
    expectedUserId: 'user-token-execution-header',
    expectedSessionId: 'session-token-execution-header',
    expectedWalletAddress: 'user-token-execution-header',
  },
  {
    label: 'execution uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-execution-upper',
    expectedToken: 'token-execution-upper',
    expectedUserId: 'user-token-execution-upper',
    expectedSessionId: 'session-token-execution-upper',
    expectedWalletAddress: 'user-token-execution-upper',
  },
  {
    label: 'execution array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-execution-array', 'Bearer ignored-token'],
    expectedToken: 'token-execution-array',
    expectedUserId: 'user-token-execution-array',
    expectedSessionId: 'session-token-execution-array',
    expectedWalletAddress: 'user-token-execution-array',
  },
  {
    label: 'custody auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-custody-feed',
    expectedToken: 'token-custody-feed',
    expectedUserId: 'user-token-custody-feed',
    expectedSessionId: 'session-token-custody-feed',
    expectedWalletAddress: 'user-token-custody-feed',
  },
  {
    label: 'custody auth bare token',
    source: 'auth',
    authToken: 'token-custody-feed-bare',
    expectedToken: 'token-custody-feed-bare',
    expectedUserId: 'user-token-custody-feed-bare',
    expectedSessionId: 'session-token-custody-feed-bare',
    expectedWalletAddress: 'user-token-custody-feed-bare',
  },
  {
    label: 'custody lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-custody-header',
    expectedToken: 'token-custody-header',
    expectedUserId: 'user-token-custody-header',
    expectedSessionId: 'session-token-custody-header',
    expectedWalletAddress: 'user-token-custody-header',
  },
  {
    label: 'custody uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-custody-upper',
    expectedToken: 'token-custody-upper',
    expectedUserId: 'user-token-custody-upper',
    expectedSessionId: 'session-token-custody-upper',
    expectedWalletAddress: 'user-token-custody-upper',
  },
  {
    label: 'custody array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-custody-array', 'Bearer ignored-token'],
    expectedToken: 'token-custody-array',
    expectedUserId: 'user-token-custody-array',
    expectedSessionId: 'session-token-custody-array',
    expectedWalletAddress: 'user-token-custody-array',
  },
  {
    label: 'history auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-history-feed',
    expectedToken: 'token-history-feed',
    expectedUserId: 'user-token-history-feed',
    expectedSessionId: 'session-token-history-feed',
    expectedWalletAddress: 'user-token-history-feed',
  },
  {
    label: 'history auth bare token',
    source: 'auth',
    authToken: 'token-history-feed-bare',
    expectedToken: 'token-history-feed-bare',
    expectedUserId: 'user-token-history-feed-bare',
    expectedSessionId: 'session-token-history-feed-bare',
    expectedWalletAddress: 'user-token-history-feed-bare',
  },
  {
    label: 'history lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-history-header',
    expectedToken: 'token-history-header',
    expectedUserId: 'user-token-history-header',
    expectedSessionId: 'session-token-history-header',
    expectedWalletAddress: 'user-token-history-header',
  },
  {
    label: 'history uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-history-upper',
    expectedToken: 'token-history-upper',
    expectedUserId: 'user-token-history-upper',
    expectedSessionId: 'session-token-history-upper',
    expectedWalletAddress: 'user-token-history-upper',
  },
  {
    label: 'history array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-history-array', 'Bearer ignored-token'],
    expectedToken: 'token-history-array',
    expectedUserId: 'user-token-history-array',
    expectedSessionId: 'session-token-history-array',
    expectedWalletAddress: 'user-token-history-array',
  },
  {
    label: 'settings auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-settings-feed',
    expectedToken: 'token-settings-feed',
    expectedUserId: 'user-token-settings-feed',
    expectedSessionId: 'session-token-settings-feed',
    expectedWalletAddress: 'user-token-settings-feed',
  },
  {
    label: 'settings auth bare token',
    source: 'auth',
    authToken: 'token-settings-feed-bare',
    expectedToken: 'token-settings-feed-bare',
    expectedUserId: 'user-token-settings-feed-bare',
    expectedSessionId: 'session-token-settings-feed-bare',
    expectedWalletAddress: 'user-token-settings-feed-bare',
  },
  {
    label: 'settings lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-settings-header',
    expectedToken: 'token-settings-header',
    expectedUserId: 'user-token-settings-header',
    expectedSessionId: 'session-token-settings-header',
    expectedWalletAddress: 'user-token-settings-header',
  },
  {
    label: 'settings uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-settings-upper',
    expectedToken: 'token-settings-upper',
    expectedUserId: 'user-token-settings-upper',
    expectedSessionId: 'session-token-settings-upper',
    expectedWalletAddress: 'user-token-settings-upper',
  },
  {
    label: 'settings array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-settings-array', 'Bearer ignored-token'],
    expectedToken: 'token-settings-array',
    expectedUserId: 'user-token-settings-array',
    expectedSessionId: 'session-token-settings-array',
    expectedWalletAddress: 'user-token-settings-array',
  },
  {
    label: 'billing auth bearer token',
    source: 'auth',
    authToken: 'Bearer token-billing-feed',
    expectedToken: 'token-billing-feed',
    expectedUserId: 'user-token-billing-feed',
    expectedSessionId: 'session-token-billing-feed',
    expectedWalletAddress: 'user-token-billing-feed',
  },
  {
    label: 'billing auth bare token',
    source: 'auth',
    authToken: 'token-billing-feed-bare',
    expectedToken: 'token-billing-feed-bare',
    expectedUserId: 'user-token-billing-feed-bare',
    expectedSessionId: 'session-token-billing-feed-bare',
    expectedWalletAddress: 'user-token-billing-feed-bare',
  },
  {
    label: 'billing lowercase header bearer token',
    source: 'authorization',
    headerToken: 'Bearer token-billing-header',
    expectedToken: 'token-billing-header',
    expectedUserId: 'user-token-billing-header',
    expectedSessionId: 'session-token-billing-header',
    expectedWalletAddress: 'user-token-billing-header',
  },
  {
    label: 'billing uppercase header bare token',
    source: 'Authorization',
    headerToken: 'token-billing-upper',
    expectedToken: 'token-billing-upper',
    expectedUserId: 'user-token-billing-upper',
    expectedSessionId: 'session-token-billing-upper',
    expectedWalletAddress: 'user-token-billing-upper',
  },
  {
    label: 'billing array header uses first token',
    source: 'authorization-array',
    headerToken: ['Bearer token-billing-array', 'Bearer ignored-token'],
    expectedToken: 'token-billing-array',
    expectedUserId: 'user-token-billing-array',
    expectedSessionId: 'session-token-billing-array',
    expectedWalletAddress: 'user-token-billing-array',
  },
  {
    label: 'header token with leading and trailing spaces',
    source: 'authorization',
    headerToken: '  Bearer token-header-spaces  ',
    expectedToken: 'token-header-spaces',
    expectedUserId: 'user-token-header-spaces',
    expectedSessionId: 'session-token-header-spaces',
    expectedWalletAddress: 'user-token-header-spaces',
  },
  {
    label: 'auth token with leading and trailing spaces',
    source: 'auth',
    authToken: '  Bearer token-auth-spaces  ',
    expectedToken: 'token-auth-spaces',
    expectedUserId: 'user-token-auth-spaces',
    expectedSessionId: 'session-token-auth-spaces',
    expectedWalletAddress: 'user-token-auth-spaces',
  },
  {
    label: 'mixed case bearer prefix in auth token',
    source: 'auth',
    authToken: 'bEaReR token-mixed-bearer',
    expectedToken: 'token-mixed-bearer',
    expectedUserId: 'user-token-mixed-bearer',
    expectedSessionId: 'session-token-mixed-bearer',
    expectedWalletAddress: 'user-token-mixed-bearer',
  },
  {
    label: 'mixed case bearer prefix in header token',
    source: 'authorization',
    headerToken: 'bEaReR token-mixed-header',
    expectedToken: 'token-mixed-header',
    expectedUserId: 'user-token-mixed-header',
    expectedSessionId: 'session-token-mixed-header',
    expectedWalletAddress: 'user-token-mixed-header',
  },
  {
    label: 'auth token takes precedence over header token',
    source: 'auth',
    authToken: 'Bearer token-auth-precedence',
    headerToken: 'Bearer token-header-ignored',
    expectedToken: 'token-auth-precedence',
    expectedUserId: 'user-token-auth-precedence',
    expectedSessionId: 'session-token-auth-precedence',
    expectedWalletAddress: 'user-token-auth-precedence',
  },
];

const REJECTED_TOKEN_MATRIX: RejectedTokenCase[] = [
  {
    label: 'missing token',
    source: 'none',
    expectedMessage: 'Missing authentication token',
  },
  {
    label: 'blank auth token',
    source: 'auth',
    authToken: '   ',
    expectedMessage: 'Missing authentication token',
  },
  {
    label: 'blank lowercase authorization header',
    source: 'authorization',
    headerToken: '   ',
    expectedMessage: 'Missing authentication token',
  },
  {
    label: 'blank uppercase authorization header',
    source: 'Authorization',
    headerToken: '   ',
    expectedMessage: 'Missing authentication token',
  },
  {
    label: 'expired auth token',
    source: 'auth',
    authToken: 'expired-auth-token',
    verifyError: 'jwt expired',
    expectedMessage: 'Invalid or expired token',
  },
  {
    label: 'malformed auth token',
    source: 'auth',
    authToken: 'malformed-auth-token',
    verifyError: 'jwt malformed',
    expectedMessage: 'Invalid or expired token',
  },
  {
    label: 'expired lowercase header token',
    source: 'authorization',
    headerToken: 'Bearer expired-header-token',
    verifyError: 'jwt expired',
    expectedMessage: 'Invalid or expired token',
  },
  {
    label: 'malformed lowercase header token',
    source: 'authorization',
    headerToken: 'Bearer malformed-header-token',
    verifyError: 'jwt malformed',
    expectedMessage: 'Invalid or expired token',
  },
  {
    label: 'expired uppercase header token',
    source: 'Authorization',
    headerToken: 'Bearer expired-upper-token',
    verifyError: 'jwt expired',
    expectedMessage: 'Invalid or expired token',
  },
  {
    label: 'malformed uppercase header token',
    source: 'Authorization',
    headerToken: 'Bearer malformed-upper-token',
    verifyError: 'jwt malformed',
    expectedMessage: 'Invalid or expired token',
  },
  {
    label: 'payload without subject',
    source: 'auth',
    authToken: 'payload-without-subject',
    payload: { sid: 'session-without-subject' },
    expectedMessage: 'Invalid token payload',
  },
  {
    label: 'payload with empty subject',
    source: 'auth',
    authToken: 'payload-empty-subject',
    payload: { sub: '', sid: 'session-empty-subject' },
    expectedMessage: 'Invalid token payload',
  },
  {
    label: 'payload with whitespace subject',
    source: 'auth',
    authToken: 'payload-whitespace-subject',
    payload: { sub: '   ', sid: 'session-whitespace-subject' },
    expectedMessage: 'Invalid token payload',
  },
  {
    label: 'payload with numeric subject',
    source: 'auth',
    authToken: 'payload-numeric-subject',
    payload: { sub: 12345, sid: 'session-numeric-subject' },
    expectedMessage: 'Invalid token payload',
  },
  {
    label: 'payload with boolean subject',
    source: 'auth',
    authToken: 'payload-boolean-subject',
    payload: { sub: true, sid: 'session-boolean-subject' },
    expectedMessage: 'Invalid token payload',
  },
  {
    label: 'payload with null subject',
    source: 'auth',
    authToken: 'payload-null-subject',
    payload: { sub: null, sid: 'session-null-subject' },
    expectedMessage: 'Invalid token payload',
  },
  {
    label: 'payload with object subject',
    source: 'auth',
    authToken: 'payload-object-subject',
    payload: { sub: { id: 'nested-user' }, sid: 'session-object-subject' },
    expectedMessage: 'Invalid token payload',
  },
  {
    label: 'header payload without subject',
    source: 'authorization',
    headerToken: 'Bearer payload-header-without-subject',
    payload: { sid: 'session-header-without-subject' },
    expectedMessage: 'Invalid token payload',
  },
  {
    label: 'uppercase header payload without subject',
    source: 'Authorization',
    headerToken: 'Bearer payload-upper-without-subject',
    payload: { sid: 'session-upper-without-subject' },
    expectedMessage: 'Invalid token payload',
  },
  {
    label: 'auth bearer prefix without actual token',
    source: 'auth',
    authToken: 'Bearer    ',
    expectedMessage: 'Missing authentication token',
  },
  {
    label: 'header bearer prefix without actual token',
    source: 'authorization',
    headerToken: 'Bearer    ',
    expectedMessage: 'Missing authentication token',
  },
  {
    label: 'revoked-looking token rejected by verifier',
    source: 'auth',
    authToken: 'revoked-session-token',
    verifyError: 'session revoked',
    expectedMessage: 'Invalid or expired token',
  },
  {
    label: 'tampered token rejected by verifier',
    source: 'auth',
    authToken: 'tampered-signature-token',
    verifyError: 'invalid signature',
    expectedMessage: 'Invalid or expired token',
  },
  {
    label: 'wrong audience token rejected by verifier',
    source: 'authorization',
    headerToken: 'Bearer wrong-audience-token',
    verifyError: 'jwt audience invalid',
    expectedMessage: 'Invalid or expired token',
  },
  {
    label: 'not-before token rejected by verifier',
    source: 'Authorization',
    headerToken: 'Bearer not-before-token',
    verifyError: 'jwt not active',
    expectedMessage: 'Invalid or expired token',
  },
];

describe('WsJwtGuard regression matrix', () => {
  let jwtService: {
    verify: jest.Mock;
  };
  let guard: WsJwtGuard;

  beforeEach(() => {
    jwtService = {
      verify: jest.fn((token: string) => ({
        sub: `user-${token}`,
        sid: `session-${token}`,
        iat: 1767225600,
        exp: 1767229200,
      })),
    };
    guard = new WsJwtGuard(jwtService as unknown as JwtService);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it.each(ACCEPTED_TOKEN_MATRIX)(
    'accepts $label',
    (tokenCase: AcceptedTokenCase) => {
      const client = makeSocket(tokenCase);

      const user = guard.validateSocket(client);

      expect(jwtService.verify).toHaveBeenCalledWith(tokenCase.expectedToken);
      expect(user).toEqual(
        expect.objectContaining({
          sub: tokenCase.expectedUserId,
          sid: tokenCase.expectedSessionId,
        }),
      );
      expect(client.data.user).toEqual(user);
      expect(client.data.walletAddress).toBe(tokenCase.expectedWalletAddress);
    },
  );

  it.each(REJECTED_TOKEN_MATRIX)(
    'rejects $label',
    (tokenCase: RejectedTokenCase) => {
      if (tokenCase.verifyError) {
        jwtService.verify.mockImplementation(() => {
          throw new Error(tokenCase.verifyError);
        });
      }

      if (tokenCase.payload) {
        jwtService.verify.mockReturnValue(tokenCase.payload);
      }

      const client = makeSocket(tokenCase);

      expect(() => guard.validateSocket(client)).toThrow(
        new UnauthorizedException(tokenCase.expectedMessage),
      );
      expect(client.data.user).toBeUndefined();
      expect(client.data.walletAddress).toBeUndefined();
    },
  );
});

function makeSocket(
  tokenCase: Pick<
    AcceptedTokenCase | RejectedTokenCase,
    'source' | 'authToken' | 'headerToken'
  >,
): Socket {
  const headers: Record<string, string | string[] | undefined> = {};
  if (tokenCase.source === 'authorization') {
    headers.authorization = tokenCase.headerToken;
  }
  if (tokenCase.source === 'Authorization') {
    headers.Authorization = tokenCase.headerToken;
  }
  if (tokenCase.source === 'authorization-array') {
    headers.authorization = tokenCase.headerToken;
  }

  return {
    id: `socket-${tokenCase.source}`,
    data: {},
    handshake: {
      auth: tokenCase.authToken ? { token: tokenCase.authToken } : {},
      headers,
    },
  } as Socket;
}
