import {
  WEBHOOK_BACKOFF_BASE_MS,
  WEBHOOK_BACKOFF_CAP_MS,
  WEBHOOK_BACKOFF_JITTER_MS,
  calculateWebhookBackoffDelay,
} from './webhook-delivery.constants';

type BackoffRegressionCase = {
  label: string;
  attempt: number;
  jitterMs: number;
  normalizedAttempt: number;
  exponentialDelay: number;
  expectedDelay: number;
};

const BACKOFF_REGRESSION_MATRIX: BackoffRegressionCase[] = [
  {
    label: 'attempt -3 clamps negative jitter',
    attempt: -3,
    jitterMs: -75,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2000,
  },
  {
    label: 'attempt -3 uses zero jitter',
    attempt: -3,
    jitterMs: 0,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2000,
  },
  {
    label: 'attempt -3 adds one millisecond jitter',
    attempt: -3,
    jitterMs: 1,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2001,
  },
  {
    label: 'attempt -3 adds 125ms jitter',
    attempt: -3,
    jitterMs: 125,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2125,
  },
  {
    label: 'attempt -3 adds 250ms jitter',
    attempt: -3,
    jitterMs: 250,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2250,
  },
  {
    label: 'attempt -3 adds 500ms jitter',
    attempt: -3,
    jitterMs: 500,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2500,
  },
  {
    label: 'attempt -3 adds 750ms jitter',
    attempt: -3,
    jitterMs: 750,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2750,
  },
  {
    label: 'attempt -3 floors fractional jitter',
    attempt: -3,
    jitterMs: 999.9,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2999,
  },
  {
    label: 'attempt -3 uses max jitter',
    attempt: -3,
    jitterMs: 1000,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 3000,
  },
  {
    label: 'attempt -3 clamps excess jitter',
    attempt: -3,
    jitterMs: 1400,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 3000,
  },
  {
    label: 'attempt 0 clamps negative jitter',
    attempt: 0,
    jitterMs: -75,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2000,
  },
  {
    label: 'attempt 0 uses zero jitter',
    attempt: 0,
    jitterMs: 0,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2000,
  },
  {
    label: 'attempt 0 adds one millisecond jitter',
    attempt: 0,
    jitterMs: 1,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2001,
  },
  {
    label: 'attempt 0 adds 125ms jitter',
    attempt: 0,
    jitterMs: 125,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2125,
  },
  {
    label: 'attempt 0 adds 250ms jitter',
    attempt: 0,
    jitterMs: 250,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2250,
  },
  {
    label: 'attempt 0 adds 500ms jitter',
    attempt: 0,
    jitterMs: 500,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2500,
  },
  {
    label: 'attempt 0 adds 750ms jitter',
    attempt: 0,
    jitterMs: 750,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2750,
  },
  {
    label: 'attempt 0 floors fractional jitter',
    attempt: 0,
    jitterMs: 999.9,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2999,
  },
  {
    label: 'attempt 0 uses max jitter',
    attempt: 0,
    jitterMs: 1000,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 3000,
  },
  {
    label: 'attempt 0 clamps excess jitter',
    attempt: 0,
    jitterMs: 1400,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 3000,
  },
  {
    label: 'attempt 1 clamps negative jitter',
    attempt: 1,
    jitterMs: -75,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2000,
  },
  {
    label: 'attempt 1 uses zero jitter',
    attempt: 1,
    jitterMs: 0,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2000,
  },
  {
    label: 'attempt 1 adds one millisecond jitter',
    attempt: 1,
    jitterMs: 1,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2001,
  },
  {
    label: 'attempt 1 adds 125ms jitter',
    attempt: 1,
    jitterMs: 125,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2125,
  },
  {
    label: 'attempt 1 adds 250ms jitter',
    attempt: 1,
    jitterMs: 250,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2250,
  },
  {
    label: 'attempt 1 adds 500ms jitter',
    attempt: 1,
    jitterMs: 500,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2500,
  },
  {
    label: 'attempt 1 adds 750ms jitter',
    attempt: 1,
    jitterMs: 750,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2750,
  },
  {
    label: 'attempt 1 floors fractional jitter',
    attempt: 1,
    jitterMs: 999.9,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2999,
  },
  {
    label: 'attempt 1 uses max jitter',
    attempt: 1,
    jitterMs: 1000,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 3000,
  },
  {
    label: 'attempt 1 clamps excess jitter',
    attempt: 1,
    jitterMs: 1400,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 3000,
  },
  {
    label: 'attempt 2 clamps negative jitter',
    attempt: 2,
    jitterMs: -75,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 4000,
  },
  {
    label: 'attempt 2 uses zero jitter',
    attempt: 2,
    jitterMs: 0,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 4000,
  },
  {
    label: 'attempt 2 adds one millisecond jitter',
    attempt: 2,
    jitterMs: 1,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 4001,
  },
  {
    label: 'attempt 2 adds 125ms jitter',
    attempt: 2,
    jitterMs: 125,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 4125,
  },
  {
    label: 'attempt 2 adds 250ms jitter',
    attempt: 2,
    jitterMs: 250,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 4250,
  },
  {
    label: 'attempt 2 adds 500ms jitter',
    attempt: 2,
    jitterMs: 500,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 4500,
  },
  {
    label: 'attempt 2 adds 750ms jitter',
    attempt: 2,
    jitterMs: 750,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 4750,
  },
  {
    label: 'attempt 2 floors fractional jitter',
    attempt: 2,
    jitterMs: 999.9,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 4999,
  },
  {
    label: 'attempt 2 uses max jitter',
    attempt: 2,
    jitterMs: 1000,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 5000,
  },
  {
    label: 'attempt 2 clamps excess jitter',
    attempt: 2,
    jitterMs: 1400,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 5000,
  },
  {
    label: 'attempt 3 clamps negative jitter',
    attempt: 3,
    jitterMs: -75,
    normalizedAttempt: 3,
    exponentialDelay: 8000,
    expectedDelay: 8000,
  },
  {
    label: 'attempt 3 uses zero jitter',
    attempt: 3,
    jitterMs: 0,
    normalizedAttempt: 3,
    exponentialDelay: 8000,
    expectedDelay: 8000,
  },
  {
    label: 'attempt 3 adds one millisecond jitter',
    attempt: 3,
    jitterMs: 1,
    normalizedAttempt: 3,
    exponentialDelay: 8000,
    expectedDelay: 8001,
  },
  {
    label: 'attempt 3 adds 125ms jitter',
    attempt: 3,
    jitterMs: 125,
    normalizedAttempt: 3,
    exponentialDelay: 8000,
    expectedDelay: 8125,
  },
  {
    label: 'attempt 3 adds 250ms jitter',
    attempt: 3,
    jitterMs: 250,
    normalizedAttempt: 3,
    exponentialDelay: 8000,
    expectedDelay: 8250,
  },
  {
    label: 'attempt 3 adds 500ms jitter',
    attempt: 3,
    jitterMs: 500,
    normalizedAttempt: 3,
    exponentialDelay: 8000,
    expectedDelay: 8500,
  },
  {
    label: 'attempt 3 adds 750ms jitter',
    attempt: 3,
    jitterMs: 750,
    normalizedAttempt: 3,
    exponentialDelay: 8000,
    expectedDelay: 8750,
  },
  {
    label: 'attempt 3 floors fractional jitter',
    attempt: 3,
    jitterMs: 999.9,
    normalizedAttempt: 3,
    exponentialDelay: 8000,
    expectedDelay: 8999,
  },
  {
    label: 'attempt 3 uses max jitter',
    attempt: 3,
    jitterMs: 1000,
    normalizedAttempt: 3,
    exponentialDelay: 8000,
    expectedDelay: 9000,
  },
  {
    label: 'attempt 3 clamps excess jitter',
    attempt: 3,
    jitterMs: 1400,
    normalizedAttempt: 3,
    exponentialDelay: 8000,
    expectedDelay: 9000,
  },
  {
    label: 'attempt 4 clamps negative jitter',
    attempt: 4,
    jitterMs: -75,
    normalizedAttempt: 4,
    exponentialDelay: 16000,
    expectedDelay: 16000,
  },
  {
    label: 'attempt 4 uses zero jitter',
    attempt: 4,
    jitterMs: 0,
    normalizedAttempt: 4,
    exponentialDelay: 16000,
    expectedDelay: 16000,
  },
  {
    label: 'attempt 4 adds one millisecond jitter',
    attempt: 4,
    jitterMs: 1,
    normalizedAttempt: 4,
    exponentialDelay: 16000,
    expectedDelay: 16001,
  },
  {
    label: 'attempt 4 adds 125ms jitter',
    attempt: 4,
    jitterMs: 125,
    normalizedAttempt: 4,
    exponentialDelay: 16000,
    expectedDelay: 16125,
  },
  {
    label: 'attempt 4 adds 250ms jitter',
    attempt: 4,
    jitterMs: 250,
    normalizedAttempt: 4,
    exponentialDelay: 16000,
    expectedDelay: 16250,
  },
  {
    label: 'attempt 4 adds 500ms jitter',
    attempt: 4,
    jitterMs: 500,
    normalizedAttempt: 4,
    exponentialDelay: 16000,
    expectedDelay: 16500,
  },
  {
    label: 'attempt 4 adds 750ms jitter',
    attempt: 4,
    jitterMs: 750,
    normalizedAttempt: 4,
    exponentialDelay: 16000,
    expectedDelay: 16750,
  },
  {
    label: 'attempt 4 floors fractional jitter',
    attempt: 4,
    jitterMs: 999.9,
    normalizedAttempt: 4,
    exponentialDelay: 16000,
    expectedDelay: 16999,
  },
  {
    label: 'attempt 4 uses max jitter',
    attempt: 4,
    jitterMs: 1000,
    normalizedAttempt: 4,
    exponentialDelay: 16000,
    expectedDelay: 17000,
  },
  {
    label: 'attempt 4 clamps excess jitter',
    attempt: 4,
    jitterMs: 1400,
    normalizedAttempt: 4,
    exponentialDelay: 16000,
    expectedDelay: 17000,
  },
  {
    label: 'attempt 5 clamps negative jitter',
    attempt: 5,
    jitterMs: -75,
    normalizedAttempt: 5,
    exponentialDelay: 32000,
    expectedDelay: 32000,
  },
  {
    label: 'attempt 5 uses zero jitter',
    attempt: 5,
    jitterMs: 0,
    normalizedAttempt: 5,
    exponentialDelay: 32000,
    expectedDelay: 32000,
  },
  {
    label: 'attempt 5 adds one millisecond jitter',
    attempt: 5,
    jitterMs: 1,
    normalizedAttempt: 5,
    exponentialDelay: 32000,
    expectedDelay: 32001,
  },
  {
    label: 'attempt 5 adds 125ms jitter',
    attempt: 5,
    jitterMs: 125,
    normalizedAttempt: 5,
    exponentialDelay: 32000,
    expectedDelay: 32125,
  },
  {
    label: 'attempt 5 adds 250ms jitter',
    attempt: 5,
    jitterMs: 250,
    normalizedAttempt: 5,
    exponentialDelay: 32000,
    expectedDelay: 32250,
  },
  {
    label: 'attempt 5 adds 500ms jitter',
    attempt: 5,
    jitterMs: 500,
    normalizedAttempt: 5,
    exponentialDelay: 32000,
    expectedDelay: 32500,
  },
  {
    label: 'attempt 5 adds 750ms jitter',
    attempt: 5,
    jitterMs: 750,
    normalizedAttempt: 5,
    exponentialDelay: 32000,
    expectedDelay: 32750,
  },
  {
    label: 'attempt 5 floors fractional jitter',
    attempt: 5,
    jitterMs: 999.9,
    normalizedAttempt: 5,
    exponentialDelay: 32000,
    expectedDelay: 32999,
  },
  {
    label: 'attempt 5 uses max jitter',
    attempt: 5,
    jitterMs: 1000,
    normalizedAttempt: 5,
    exponentialDelay: 32000,
    expectedDelay: 33000,
  },
  {
    label: 'attempt 5 clamps excess jitter',
    attempt: 5,
    jitterMs: 1400,
    normalizedAttempt: 5,
    exponentialDelay: 32000,
    expectedDelay: 33000,
  },
  {
    label: 'attempt 6 clamps negative jitter',
    attempt: 6,
    jitterMs: -75,
    normalizedAttempt: 6,
    exponentialDelay: 64000,
    expectedDelay: 64000,
  },
  {
    label: 'attempt 6 uses zero jitter',
    attempt: 6,
    jitterMs: 0,
    normalizedAttempt: 6,
    exponentialDelay: 64000,
    expectedDelay: 64000,
  },
  {
    label: 'attempt 6 adds one millisecond jitter',
    attempt: 6,
    jitterMs: 1,
    normalizedAttempt: 6,
    exponentialDelay: 64000,
    expectedDelay: 64001,
  },
  {
    label: 'attempt 6 adds 125ms jitter',
    attempt: 6,
    jitterMs: 125,
    normalizedAttempt: 6,
    exponentialDelay: 64000,
    expectedDelay: 64125,
  },
  {
    label: 'attempt 6 adds 250ms jitter',
    attempt: 6,
    jitterMs: 250,
    normalizedAttempt: 6,
    exponentialDelay: 64000,
    expectedDelay: 64250,
  },
  {
    label: 'attempt 6 adds 500ms jitter',
    attempt: 6,
    jitterMs: 500,
    normalizedAttempt: 6,
    exponentialDelay: 64000,
    expectedDelay: 64500,
  },
  {
    label: 'attempt 6 adds 750ms jitter',
    attempt: 6,
    jitterMs: 750,
    normalizedAttempt: 6,
    exponentialDelay: 64000,
    expectedDelay: 64750,
  },
  {
    label: 'attempt 6 floors fractional jitter',
    attempt: 6,
    jitterMs: 999.9,
    normalizedAttempt: 6,
    exponentialDelay: 64000,
    expectedDelay: 64999,
  },
  {
    label: 'attempt 6 uses max jitter',
    attempt: 6,
    jitterMs: 1000,
    normalizedAttempt: 6,
    exponentialDelay: 64000,
    expectedDelay: 65000,
  },
  {
    label: 'attempt 6 clamps excess jitter',
    attempt: 6,
    jitterMs: 1400,
    normalizedAttempt: 6,
    exponentialDelay: 64000,
    expectedDelay: 65000,
  },
  {
    label: 'attempt 7 clamps negative jitter',
    attempt: 7,
    jitterMs: -75,
    normalizedAttempt: 7,
    exponentialDelay: 64000,
    expectedDelay: 64000,
  },
  {
    label: 'attempt 7 uses zero jitter',
    attempt: 7,
    jitterMs: 0,
    normalizedAttempt: 7,
    exponentialDelay: 64000,
    expectedDelay: 64000,
  },
  {
    label: 'attempt 7 adds one millisecond jitter',
    attempt: 7,
    jitterMs: 1,
    normalizedAttempt: 7,
    exponentialDelay: 64000,
    expectedDelay: 64001,
  },
  {
    label: 'attempt 7 adds 125ms jitter',
    attempt: 7,
    jitterMs: 125,
    normalizedAttempt: 7,
    exponentialDelay: 64000,
    expectedDelay: 64125,
  },
  {
    label: 'attempt 7 adds 250ms jitter',
    attempt: 7,
    jitterMs: 250,
    normalizedAttempt: 7,
    exponentialDelay: 64000,
    expectedDelay: 64250,
  },
  {
    label: 'attempt 7 adds 500ms jitter',
    attempt: 7,
    jitterMs: 500,
    normalizedAttempt: 7,
    exponentialDelay: 64000,
    expectedDelay: 64500,
  },
  {
    label: 'attempt 7 adds 750ms jitter',
    attempt: 7,
    jitterMs: 750,
    normalizedAttempt: 7,
    exponentialDelay: 64000,
    expectedDelay: 64750,
  },
  {
    label: 'attempt 7 floors fractional jitter',
    attempt: 7,
    jitterMs: 999.9,
    normalizedAttempt: 7,
    exponentialDelay: 64000,
    expectedDelay: 64999,
  },
  {
    label: 'attempt 7 uses max jitter',
    attempt: 7,
    jitterMs: 1000,
    normalizedAttempt: 7,
    exponentialDelay: 64000,
    expectedDelay: 65000,
  },
  {
    label: 'attempt 7 clamps excess jitter',
    attempt: 7,
    jitterMs: 1400,
    normalizedAttempt: 7,
    exponentialDelay: 64000,
    expectedDelay: 65000,
  },
  {
    label: 'attempt 8 clamps negative jitter',
    attempt: 8,
    jitterMs: -75,
    normalizedAttempt: 8,
    exponentialDelay: 64000,
    expectedDelay: 64000,
  },
  {
    label: 'attempt 8 uses zero jitter',
    attempt: 8,
    jitterMs: 0,
    normalizedAttempt: 8,
    exponentialDelay: 64000,
    expectedDelay: 64000,
  },
  {
    label: 'attempt 8 adds one millisecond jitter',
    attempt: 8,
    jitterMs: 1,
    normalizedAttempt: 8,
    exponentialDelay: 64000,
    expectedDelay: 64001,
  },
  {
    label: 'attempt 8 adds 125ms jitter',
    attempt: 8,
    jitterMs: 125,
    normalizedAttempt: 8,
    exponentialDelay: 64000,
    expectedDelay: 64125,
  },
  {
    label: 'attempt 8 adds 250ms jitter',
    attempt: 8,
    jitterMs: 250,
    normalizedAttempt: 8,
    exponentialDelay: 64000,
    expectedDelay: 64250,
  },
  {
    label: 'attempt 8 adds 500ms jitter',
    attempt: 8,
    jitterMs: 500,
    normalizedAttempt: 8,
    exponentialDelay: 64000,
    expectedDelay: 64500,
  },
  {
    label: 'attempt 8 adds 750ms jitter',
    attempt: 8,
    jitterMs: 750,
    normalizedAttempt: 8,
    exponentialDelay: 64000,
    expectedDelay: 64750,
  },
  {
    label: 'attempt 8 floors fractional jitter',
    attempt: 8,
    jitterMs: 999.9,
    normalizedAttempt: 8,
    exponentialDelay: 64000,
    expectedDelay: 64999,
  },
  {
    label: 'attempt 8 uses max jitter',
    attempt: 8,
    jitterMs: 1000,
    normalizedAttempt: 8,
    exponentialDelay: 64000,
    expectedDelay: 65000,
  },
  {
    label: 'attempt 8 clamps excess jitter',
    attempt: 8,
    jitterMs: 1400,
    normalizedAttempt: 8,
    exponentialDelay: 64000,
    expectedDelay: 65000,
  },
  {
    label: 'attempt 9 clamps negative jitter',
    attempt: 9,
    jitterMs: -75,
    normalizedAttempt: 9,
    exponentialDelay: 64000,
    expectedDelay: 64000,
  },
  {
    label: 'attempt 9 uses zero jitter',
    attempt: 9,
    jitterMs: 0,
    normalizedAttempt: 9,
    exponentialDelay: 64000,
    expectedDelay: 64000,
  },
  {
    label: 'attempt 9 adds one millisecond jitter',
    attempt: 9,
    jitterMs: 1,
    normalizedAttempt: 9,
    exponentialDelay: 64000,
    expectedDelay: 64001,
  },
  {
    label: 'attempt 9 adds 125ms jitter',
    attempt: 9,
    jitterMs: 125,
    normalizedAttempt: 9,
    exponentialDelay: 64000,
    expectedDelay: 64125,
  },
  {
    label: 'attempt 9 adds 250ms jitter',
    attempt: 9,
    jitterMs: 250,
    normalizedAttempt: 9,
    exponentialDelay: 64000,
    expectedDelay: 64250,
  },
  {
    label: 'attempt 9 adds 500ms jitter',
    attempt: 9,
    jitterMs: 500,
    normalizedAttempt: 9,
    exponentialDelay: 64000,
    expectedDelay: 64500,
  },
  {
    label: 'attempt 9 adds 750ms jitter',
    attempt: 9,
    jitterMs: 750,
    normalizedAttempt: 9,
    exponentialDelay: 64000,
    expectedDelay: 64750,
  },
  {
    label: 'attempt 9 floors fractional jitter',
    attempt: 9,
    jitterMs: 999.9,
    normalizedAttempt: 9,
    exponentialDelay: 64000,
    expectedDelay: 64999,
  },
  {
    label: 'attempt 9 uses max jitter',
    attempt: 9,
    jitterMs: 1000,
    normalizedAttempt: 9,
    exponentialDelay: 64000,
    expectedDelay: 65000,
  },
  {
    label: 'attempt 9 clamps excess jitter',
    attempt: 9,
    jitterMs: 1400,
    normalizedAttempt: 9,
    exponentialDelay: 64000,
    expectedDelay: 65000,
  },
  {
    label: 'attempt 12 clamps negative jitter',
    attempt: 12,
    jitterMs: -75,
    normalizedAttempt: 12,
    exponentialDelay: 64000,
    expectedDelay: 64000,
  },
  {
    label: 'attempt 12 uses zero jitter',
    attempt: 12,
    jitterMs: 0,
    normalizedAttempt: 12,
    exponentialDelay: 64000,
    expectedDelay: 64000,
  },
  {
    label: 'attempt 12 adds one millisecond jitter',
    attempt: 12,
    jitterMs: 1,
    normalizedAttempt: 12,
    exponentialDelay: 64000,
    expectedDelay: 64001,
  },
  {
    label: 'attempt 12 adds 125ms jitter',
    attempt: 12,
    jitterMs: 125,
    normalizedAttempt: 12,
    exponentialDelay: 64000,
    expectedDelay: 64125,
  },
  {
    label: 'attempt 12 adds 250ms jitter',
    attempt: 12,
    jitterMs: 250,
    normalizedAttempt: 12,
    exponentialDelay: 64000,
    expectedDelay: 64250,
  },
  {
    label: 'attempt 12 adds 500ms jitter',
    attempt: 12,
    jitterMs: 500,
    normalizedAttempt: 12,
    exponentialDelay: 64000,
    expectedDelay: 64500,
  },
  {
    label: 'attempt 12 adds 750ms jitter',
    attempt: 12,
    jitterMs: 750,
    normalizedAttempt: 12,
    exponentialDelay: 64000,
    expectedDelay: 64750,
  },
  {
    label: 'attempt 12 floors fractional jitter',
    attempt: 12,
    jitterMs: 999.9,
    normalizedAttempt: 12,
    exponentialDelay: 64000,
    expectedDelay: 64999,
  },
  {
    label: 'attempt 12 uses max jitter',
    attempt: 12,
    jitterMs: 1000,
    normalizedAttempt: 12,
    exponentialDelay: 64000,
    expectedDelay: 65000,
  },
  {
    label: 'attempt 12 clamps excess jitter',
    attempt: 12,
    jitterMs: 1400,
    normalizedAttempt: 12,
    exponentialDelay: 64000,
    expectedDelay: 65000,
  },
];

const FRACTIONAL_ATTEMPT_MATRIX: BackoffRegressionCase[] = [
  {
    label: 'attempt 1.1 floors to first attempt',
    attempt: 1.1,
    jitterMs: 333,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2333,
  },
  {
    label: 'attempt 1.9 floors to first attempt',
    attempt: 1.9,
    jitterMs: 333,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2333,
  },
  {
    label: 'attempt 2.1 floors to second attempt',
    attempt: 2.1,
    jitterMs: 333,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 4333,
  },
  {
    label: 'attempt 2.9 floors to second attempt',
    attempt: 2.9,
    jitterMs: 333,
    normalizedAttempt: 2,
    exponentialDelay: 4000,
    expectedDelay: 4333,
  },
  {
    label: 'attempt 5.8 floors before cap calculation',
    attempt: 5.8,
    jitterMs: 333,
    normalizedAttempt: 5,
    exponentialDelay: 32000,
    expectedDelay: 32333,
  },
  {
    label: 'attempt 6.1 floors into capped delay',
    attempt: 6.1,
    jitterMs: 333,
    normalizedAttempt: 6,
    exponentialDelay: 64000,
    expectedDelay: 64333,
  },
];

const NON_FINITE_ATTEMPT_MATRIX: BackoffRegressionCase[] = [
  {
    label: 'NaN attempt falls back to first retry delay',
    attempt: Number.NaN,
    jitterMs: 250,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2250,
  },
  {
    label: 'positive infinity attempt falls back to first retry delay',
    attempt: Number.POSITIVE_INFINITY,
    jitterMs: 250,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2250,
  },
  {
    label: 'negative infinity attempt falls back to first retry delay',
    attempt: Number.NEGATIVE_INFINITY,
    jitterMs: 250,
    normalizedAttempt: 1,
    exponentialDelay: 2000,
    expectedDelay: 2250,
  },
];

describe('webhook delivery backoff regression matrix', () => {
  it.each(BACKOFF_REGRESSION_MATRIX)(
    'calculates deterministic delay for $label',
    (testCase) => {
      expect(
        calculateWebhookBackoffDelay(testCase.attempt, testCase.jitterMs),
      ).toBe(testCase.expectedDelay);
    },
  );

  it.each(BACKOFF_REGRESSION_MATRIX)(
    'keeps $label inside the configured retry envelope',
    (testCase) => {
      expect(testCase.exponentialDelay).toBe(
        Math.min(
          Math.pow(2, testCase.normalizedAttempt) * WEBHOOK_BACKOFF_BASE_MS,
          WEBHOOK_BACKOFF_CAP_MS,
        ),
      );
      expect(testCase.expectedDelay).toBeGreaterThanOrEqual(
        testCase.exponentialDelay,
      );
      expect(testCase.expectedDelay).toBeLessThanOrEqual(
        testCase.exponentialDelay + WEBHOOK_BACKOFF_JITTER_MS,
      );
    },
  );

  it.each(FRACTIONAL_ATTEMPT_MATRIX)(
    'floors fractional BullMQ attempt values for $label',
    (testCase) => {
      expect(
        calculateWebhookBackoffDelay(testCase.attempt, testCase.jitterMs),
      ).toBe(testCase.expectedDelay);
    },
  );

  it.each(NON_FINITE_ATTEMPT_MATRIX)(
    'never returns NaN for $label',
    (testCase) => {
      expect(
        calculateWebhookBackoffDelay(testCase.attempt, testCase.jitterMs),
      ).toBe(testCase.expectedDelay);
    },
  );
});
